### ISSUE TITLE
Keypad resize 2.0

### ISSUE THREAD

**Issue by danvim** [danvim/Procal#18]
![capture](https://cloud.githubusercontent.com/assets/5255292/21878141/21e59f90-d8cb-11e6-819c-f72088f36486.PNG)

The smaller buttons after resize doesn't have the same height with the larger buttons in the same row

**Comment by dipsywong98** [comment]
actually I think this is beautiful

**Comment by danvim** [comment]
@dipsywong98 No, the keypad is good now. There is another issue, because I had to set a fix height to the Large buttons, there should be a resize issue aside from padding. Sorry 😢 .

**Comment by dipsywong98** [comment]
Add this line can solve

```mainButton.setHeight((int)(mainButton.getHeight()*ratio));```

**Comment by dipsywong98** [comment]
but need to change height
I don't know whether you allow me to change the height

**Comment by dipsywong98** [comment]
now the dynamic resize is working in commit 1caa3dfac5d0bad62d43e0b8877a9111332951d9
just adopting the above method
I just close this issue
