### ISSUE TITLE
Cursor hiding when resultDisplay shows result or error, re-show when input

### ISSUE THREAD

**Issue by bryanchun** [danvim/Procal#28]
Hopefully setting cursor at first or last cursor position
Like in fx50, left arrow and right arrow

**Comment by dipsywong98** [comment]
you can see some basic effect in commit 753d92db66f8ecf7b8d326b3e6dc070865e5f232
If you think this is alright you can merge

**Comment by dipsywong98** [comment]
Done in commit 7510bd8374628a4316e47110f3a0e8e45daefee2
