### ISSUE TITLE
Bugs known after putting Procal and ProcalParsing together

### ISSUE THREAD

**Issue by bryanchun** [danvim/Procal#29]
1. sin(&pi) = 0E-15
2. sin(&pi&pi) = 0.430301217-
3. If 1:Then 2:Else 3: IfEnd >>> Procal wholly crashes; Colon recognised after Suffix Function (lbp)

n. 5-6 sec wait to launch

**Comment by dipsywong98** [comment]
type:
0 EXE
ANS + 1 EXE
EXE
EXE

generate:

0
1
3
5

similar thing happens with M+ and M-

**Comment by dipsywong98** [comment]
negative display as number-

like -9 display as 9-

**Comment by dipsywong98** [comment]
x^-1 button fail
parsing error

**Comment by danvim** [comment]
Fixed?
