### ISSUE TITLE
Downgrade to Lollipop with RetroLambda and supportstream

### ISSUE THREAD

**Issue by bryanchun** [danvim/Procal#31]

**Comment by bryanchun** [comment]
Please note that this is of lower priority, concerning the integrity of Procal rather than having more device compatible.

**Comment by danvim** [comment]
Done retrolambda

**Comment by danvim** [comment]
Done streamsupport

**Comment by danvim** [comment]
Should be done in commit 25048f34cb4c849fc49ef0639d1e4b966f2e33e9
