### ISSUE TITLE
Cursor and Scrollable: Matrix display when tapped on

### ISSUE THREAD

**Issue by danvim** [danvim/Procal#6]
1. Make a cursor and display with the `|` character in font Fx50.
2. Make the cursor movable between tokens when the matrix display is tapped on by the user.
3. span {sin(, ), 3, 8, \omega}

**Comment by danvim** [comment]
Maybe will change textview to edittext

**Comment by danvim** [comment]
Check whether `TextView` without a listener can block a click event to a view below. If so, look for whether there is a non interactable tag for a `View`

![untitled-1-01](https://cloud.githubusercontent.com/assets/5255292/21843005/2fca3348-d824-11e6-9bd9-cd2b2a81c994.png)

- TextView Input (wrap content, wrap content)
- TextView Cursor (match parant, wrap content)
- Linear Layout (wrap content, wrap content)
- Horizontal Scroll View (match parent, match parent)

**Comment by bryanchun** [comment]
This maybe helpful for the "prevent keyboard from popuping up" issue, in case we use `EditText`:
```java
public class CalculatorEditText extends EditText {
    //...
    @Override
    public boolean onTouchEvent(MotionEvent event) {
        if (event.getActionMasked() == MotionEvent.ACTION_UP) {
            // Hack to prevent keyboard and insertion handle from showing.
            cancelLongPress();
        }
        return super.onTouchEvent(event);
    }
}
```
https://github.com/android/platform_packages_apps_calculator/blob/master/src/com/android/calculator2/CalculatorEditText.java

**Comment by dipsywong98** [comment]
sorry forget to mention, my computer fail to generate wifi
cursor is working in commit 4aec388c5607d70587faf6319c510bf2fe518987
but merge of branch is needed

**Comment by dipsywong98** [comment]
but there is still some bug need to resolve, like wrong cursor position clicking sin when scrolled

**Comment by dipsywong98** [comment]
by the way, I did't change to edittext

**Comment by dipsywong98** [comment]
wrong cursor position when scrolled after tapping token solved in commit 6a5a16ff2917c8ca99d76ff932b1a0dd2f9dac9a

**Comment by dipsywong98** [comment]
now the cursor cannot go to the right most position by tapping matrix display
I will solve this later

**Comment by dipsywong98** [comment]
more user friendly tapping cursor is finished in commit 9611ba6ca88b0d1a714a0b6d6464bc16402895c1

**Comment by dipsywong98** [comment]
auto scroll added in commit 2a3bb2546e30e9db128afc5b9d332c15f63cd10d
